version: '3.8'

services:
  web:
    container_name: bugtracker_web
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: sh -c "PYTHONPATH=./bugtracker DJANGO_SETTINGS_MODULE=bugtracker.settings gunicorn bugtracker.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/bugtracker/staticfiles
      - media_volume:/home/app/web/bugtracker/mediafiles4
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: bugtracker_db
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    container_name: bugtracker_nginx
    volumes:
      - static_volume:/home/app/web/bugtracker/staticfiles
      - media_volume:/home/app/web/bugtracker/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: